[program:bench-frappe-web]
command=/home/frappe/frappe-bench/env/bin/gunicorn frappe.app:application --bind 0.0.0.0:8000 --worker-class=gthread --workers=1 --threads=2 --timeout 120 --graceful-timeout 30 --preload
priority=2
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=frappe
directory=/home/frappe/frappe-bench/sites

[program:bench-node-socketio]
command=$NODE_PATH /home/frappe/frappe-bench/apps/frappe/socketio.js
priority=2
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=frappe
directory=/home/frappe/frappe-bench

[group:bench-web]
programs=bench-frappe-web,bench-node-socketio

[program:bench-frappe-default-worker]
command=$BENCH_PATH worker --queue default
priority=4
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=frappe
stopwaitsecs=1560
directory=/home/frappe/frappe-bench
killasgroup=true
numprocs=3
process_name=%(program_name)s-%(process_num)d
environment=HOME="/home/frappe"

[program:bench-frappe-short-worker]
command=$BENCH_PATH worker --queue short
priority=4
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=frappe
stopwaitsecs=360
directory=/home/frappe/frappe-bench
killasgroup=true
numprocs=3
process_name=%(program_name)s-%(process_num)d
environment=HOME="/home/frappe"

[program:bench-frappe-long-worker]
command=$BENCH_PATH worker --queue long
priority=4
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=frappe
stopwaitsecs=1560
directory=/home/frappe/frappe-bench
killasgroup=true
numprocs=3
process_name=%(program_name)s-%(process_num)d
environment=HOME="/home/frappe"

[program:bench-frappe-schedule]
command=$BENCH_PATH schedule
priority=3
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=frappe
directory=/home/frappe/frappe-bench
environment=HOME="/home/frappe"

[group:bench-workers]
programs=bench-frappe-default-worker,bench-frappe-short-worker,bench-frappe-long-worker,bench-frappe-schedule

[supervisord]
nodaemon=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[supervisorctl]
